# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BlacksmithEnterprise < Formula
  desc "The Blacksmith CLI allows to manage and run Blacksmith applications."
  homepage "https://nunchi.studio/blacksmith"
  version "0.18.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nunchistudio/blacksmith/releases/download/v0.18.0/blacksmith-cli-enterprise_v0.18.0_darwin-amd64.zip"
      sha256 "f3b339c75cf892ddfb3ef2cccb094351d268cf1251d40d821fed2544a17f7bdd"
    end
    if Hardware::CPU.arm?
      url "https://github.com/nunchistudio/blacksmith/releases/download/v0.18.0/blacksmith-cli-enterprise_v0.18.0_darwin-arm64.zip"
      sha256 "5f5490322669a2bdd7d5a55bb4ba01e5b8a490b6e5c37ec9542fddf9a7581b4a"
    end

    depends_on arch: [:x86_64, :aarch64]
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nunchistudio/blacksmith/releases/download/v0.18.0/blacksmith-cli-enterprise_v0.18.0_linux-amd64.zip"
      sha256 "1a2785689b8584ea5245ace2d6be8055a4d496b0b8fa98d8140f5f8846653bb2"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nunchistudio/blacksmith/releases/download/v0.18.0/blacksmith-cli-enterprise_v0.18.0_linux-arm.zip"
      sha256 "14b08937a3def3eab349a23482a606a6936b670c5b744f4bf9c3d2cc98d47ad8"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nunchistudio/blacksmith/releases/download/v0.18.0/blacksmith-cli-enterprise_v0.18.0_linux-arm64.zip"
      sha256 "b40322444d4b704678e6f4aebe35b639cb3f3316d4c6bc921037fbb9b8b63c94"
    end

    depends_on arch: [:x86_64, :aarch64, :arm]
  end

  depends_on "go" => :optional
  depends_on "docker" => :optional

  def install
    bin.install "blacksmith"
  end
end
