# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BlacksmithStandard < Formula
  desc "The Blacksmith CLI allows to manage and run Blacksmith applications."
  homepage "https://nunchi.studio/blacksmith"
  version "0.17.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/nunchistudio/blacksmith/releases/download/v0.17.0/blacksmith-cli-standard_v0.17.0_darwin-amd64.zip"
    sha256 "8215c7f524c7fa9cd183b92048afaf65cc6f7d7f362f9e97d8191174d72b5901"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/nunchistudio/blacksmith/releases/download/v0.17.0/blacksmith-cli-standard_v0.17.0_darwin-arm64.zip"
    sha256 "8dff5661f414ea7bc21f80988fde0204bfa804f9a6b8c1aaede56e2108e85cd4"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/nunchistudio/blacksmith/releases/download/v0.17.0/blacksmith-cli-standard_v0.17.0_linux-amd64.zip"
    sha256 "2dd24e357a476fc6220f4dc85a569423b12c1fa25440c572abf347b38d26246f"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/nunchistudio/blacksmith/releases/download/v0.17.0/blacksmith-cli-standard_v0.17.0_linux-arm.zip"
    sha256 "2ac3d2cfe26be1de13b2fb9216ab2a0dd4a0b4ad3496f76998f3bf908158c233"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/nunchistudio/blacksmith/releases/download/v0.17.0/blacksmith-cli-standard_v0.17.0_linux-arm64.zip"
    sha256 "6cafbc7a4c82cdb7c053e477769578093d50704591128769b5573d47ad4cc23b"
  end

  depends_on "go" => :optional
  depends_on "docker" => :optional

  def install
    bin.install "blacksmith"
  end
end
