# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BlacksmithEnterprise < Formula
  desc "The Blacksmith CLI allows to manage and run Blacksmith applications."
  homepage "https://nunchi.studio/blacksmith"
  version "0.17.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/nunchistudio/blacksmith/releases/download/v0.17.0/blacksmith-cli-enterprise_v0.17.0_darwin-amd64.zip"
    sha256 "da823d9ce7550b419cd526ca447a0016eb338d1f96647557ee60f90e9e53185f"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/nunchistudio/blacksmith/releases/download/v0.17.0/blacksmith-cli-enterprise_v0.17.0_darwin-arm64.zip"
    sha256 "0a1b4acaef528c0dba300fdc413fe246b1209e8a0e0101cf13037c3dfc15a5b5"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/nunchistudio/blacksmith/releases/download/v0.17.0/blacksmith-cli-enterprise_v0.17.0_linux-amd64.zip"
    sha256 "c0e717b17f4eb035465c6dd169a95ec017e260b737933973e0d7f18feb12943c"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/nunchistudio/blacksmith/releases/download/v0.17.0/blacksmith-cli-enterprise_v0.17.0_linux-arm.zip"
    sha256 "4b0d8680eb33749a6400c17fc955690c9552d08adde90edcfe9726ce58f6de3a"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/nunchistudio/blacksmith/releases/download/v0.17.0/blacksmith-cli-enterprise_v0.17.0_linux-arm64.zip"
    sha256 "eef4322c89009d1d5942dab62dd07f164627d16b9e437e4ea39ea8d5b46d4335"
  end

  depends_on "go" => :optional
  depends_on "docker" => :optional

  def install
    bin.install "blacksmith"
  end
end
